spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://awseb-e-f5ag2zxngr-stack-awsebrdsdatabase-enrque9aupvj.cctwsjp5oovj.us-east-1.rds.amazonaws.com:3306/homepage
    username: sa
    password: '__NAelen0328'
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 5000
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    env:
      enabled: true
      show-values: WHEN_AUTHORIZED