spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/homepage
    username: sa
    password: '@@NAelen0328'
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  error:
    include-stacktrace: always
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    env:
      enabled: true
app:
  login:
    redirect: "/"